/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndkeclipse_JniClient */

#ifndef _Included_com_example_testndkeclipse_JniClient
#define _Included_com_example_testndkeclipse_JniClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
