document.writeln("<body topmargin=\"0\" leftmargin=\"0\" bgcolor=\"#FFFFFF\">");
document.writeln("");
document.writeln("<table class=\"Bottom_tdbgall\" style=\"WORD-BREAK: break-all\" cellSpacing=\"0\" cellPadding=\"0\" width=\"760\" align=\"center\" border=\"0\">");
document.writeln("	<tr align=\"middle\">");
document.writeln("		<td class=\"Bottom_Adminlogo\" colSpan=\"2\">|");
document.writeln("		<a class=\"Bottom\" onclick=\"this.style.behavior=\'url(#default#homepage)\';this.setHomePage(\'http:\/\/www.ffboy.com\');\" href=\"#\">");
document.writeln("		设为首页<\/a> |");
document.writeln("		<a class=\"Bottom\" href=\"javascript:window.external.addFavorite(\'http:\/\/www.ffboy.com\',\'峰峰网络\');\">");
document.writeln("		加入收藏<\/a> | <a class=\"Bottom\" href=\"mailto:fengfeng1980629@tom.com\">联系站长<\/a> ");
document.writeln("		|");
document.writeln("		<a class=\"Bottom\" target=\"_blank\" href=\"http:\/\/www.ffboy.com\/FriendSite\/Index.asp\">");
document.writeln("		友情链接<\/a> |");
document.writeln("		<a class=\"Bottom\" target=\"_blank\" href=\"http:\/\/www.ffboy.com\/Copyright.asp\">");
document.writeln("		版权申明<\/a> | <\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr bgColor=\"#ff8900\">");
document.writeln("		<td colSpan=\"2\" height=\"7\"><\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr class=\"Bottom_Copyright\">");
document.writeln("		<td width=\"20%\" height=\"68\">");
document.writeln("		<img src=\"http:\/\/www.ffboy.com\/Skin\/blue\/powerease_logo.gif\"><\/td>");
document.writeln("		<td align=\"middle\" width=\"80%\">");
document.writeln("		<style>");
document.writeln("<!--");
document.writeln(".style3 {color: #FFFF66}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("		<table cellSpacing=\"0\" cellPadding=\"0\" width=\"542\" border=\"0\">");
document.writeln("			<tr>");
document.writeln("				<td vAlign=\"bottom\">");
document.writeln("<p align=\"center\">峰峰网络版权所有&nbsp;&nbsp; ");
document.writeln("<a target=\"_blank\" href=\"http:\/\/www.miibeian.gov.cn\/\">晋ICP备05003698号<\/a><\/br>");
document.writeln("建议使用：1024*768分辨率，16位以上颜色、<br>");
document.writeln("Netscape6.0、IE5.0以上版本浏览器和中文大字符集<br>");
document.writeln("站长:丁润峰<\/td>");
document.writeln("				<td width=\"114\">");
document.writeln("				<p align=\"center\">　<script language=\"JavaScript\" type=\"text\/javascript\" src=\"http:\/\/www.50bang.com\/click.js?user_id=2484\"><\/script>						   <\/p><script src=\"http:\/\/count3.51yes.com\/click.aspx?id=33394847&logo=1\"><\/script><\/td>");
document.writeln("			<\/tr>");
document.writeln("			<\/table>");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("<\/table>");
document.writeln("")